linters-settings:
  golint:
    min-confidence: 0
  misspell:
    locale: US

linters:
  disable-all: false
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - ineffassign
    - gosimple
    - unused
    - errcheck
    - staticcheck
    - gofmt
    - bodyclose
    - loggercheck
    - nilerr

run:
  timeout: 10m
