linters:
  disable-all: false
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - ineffassign
    - gosimple
    - unused
    - errcheck
    - staticcheck
    - gofmt
    - bodyclose
    - loggercheck
    - nilerr
    - prealloc
    - predeclared
    - durationcheck
    - makezero
    - exportloopref
    - rowserrcheck
    - stylecheck
    - gosec

run:
  timeout: 10m

linters-settings:
  stylecheck:
    checks: ["-ST1003"]
  gosec:
    excludes:
      - G306
      - G402
      - G404
  golint:
    min-confidence: 0
  misspell:
    locale: US

