basePath: /api/v1
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  user.LoginRequest:
    properties:
      username:
        description: 用户名
        type: string
    type: object
  user.LoginResponse:
    properties:
      username:
        description: 用户名
        type: string
    type: object
  user.LogoutRequest:
    type: object
  user.LogoutResponse:
    type: object
  user.RegisterRequest:
    properties:
      username:
        description: 用户名
        type: string
    type: object
  user.RegisterResponse:
    type: object
info:
  title: api文档
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LoginResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登录
      tags:
      - user
  /user/logout:
    delete:
      consumes:
      - application/json
      description: 登出
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LogoutResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登出
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.RegisterResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 注册
      tags:
      - user
swagger: "2.0"
