basePath: /api/v1
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  example.AuditRequest:
    type: object
  example.AuditResponse:
    type: object
  example.GinFunResponse:
    type: object
  example.PingResponse:
    properties:
      pong:
        type: string
    type: object
  user.CurrentUserResponse:
    properties:
      username:
        type: string
    type: object
  user.LoginRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  user.LoginResponse:
    properties:
      username:
        type: string
    type: object
  user.LogoutResponse:
    type: object
  user.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  user.RefreshTokenResponse:
    properties:
      username:
        type: string
    type: object
  user.RegisterRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  user.RegisterResponse:
    type: object
info:
  title: api文档
  version: "1.0"
paths:
  /example/audit:
    post:
      consumes:
      - application/json
      description: 审计操作
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/example.AuditRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/example.AuditResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 审计操作
      tags:
      - example
  /example/gin-fun:
    get:
      consumes:
      - application/json
      description: gin function
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/example.GinFunResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: gin function
      tags:
      - example
  /example/ping:
    get:
      consumes:
      - application/json
      description: ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/example.PingResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: ping
      tags:
      - example
  /user/current:
    get:
      consumes:
      - application/json
      description: 当前登录用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.CurrentUserResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 当前登录用户
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LoginResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登录
      tags:
      - user
  /user/logout:
    get:
      consumes:
      - application/json
      description: 登出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LogoutResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登出
      tags:
      - user
  /user/refresh:
    post:
      consumes:
      - application/json
      description: 刷新token
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.RefreshTokenResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 刷新token
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.RegisterResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 注册
      tags:
      - user
swagger: "2.0"
